version: 2.1
jobs:
  build:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: 'npm ci'
      - run:
          name: 'Build SDK'
          command: 'npm run build'
      - run:
          name: 'Audit dependencies'
          command: 'npm audit'
      - run:
          name: 'Run tests'
          command: 'npm test'
